{
  "openapi": "3.0.0",
  "info": {
    "title": "MLBB DOCS",
    "description": "Documentation for mobile legends api .",
    "version": "1"
  },
  "servers": [
    {
      "url": "https://mlbb-api.vercel.app/",
      "description": "SwaggerHub API Mobile Legends"
    }
  ],
  "paths": {
    "/heroes": {
      "get": {
        "tags": [
          "heroes"
        ],
        "summary": "Returns the first 10 heroes on the list",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "example": {
                  "message": "Sucessfuly",
                  "heroes": [
                    {
                      "hero_id": 4,
                      "name": "Alice",
                      "roles": "Mage",
                      "specialties": "Charge",
                      "lane": "Jungler",
                      "release_year": 2016,
                      "img_hero": "https://images-for-api-ml.vercel.app/alice"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/heroes/": {
      "get": {
        "tags": [
          "heroes"
        ],
        "summary": "Returns 10 heroes from the tenth",
        "parameters": [
          {
            "name": "offset",
            "in": "query",
            "description": "",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "minimum": 0,
              "type": "integer"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "maximum": 100,
              "minimum": 1,
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "message": "Sucessfuly",
                  "heroes": [
                    {
                      "hero_id": 4,
                      "name": "Alice",
                      "roles": "Mage",
                      "specialties": "Charge",
                      "lane": "Jungler",
                      "release_year": 2016,
                      "img_hero": "https://images-for-api-ml.vercel.app/alice"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/heroes/{name}": {
      "get": {
        "tags": [
          "heroes"
        ],
        "summary": "Returns the hero by name",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "example": {
                  "message": "Sucessfuly",
                  "hero": {
                    "hero_id": 1,
                    "name": "Alice",
                    "roles": "Mage",
                    "specialties": "Charge",
                    "lane": "Jungler",
                    "release_year": 2016,
                    "img_hero": "https://images-for-api-ml.vercel.app/alice"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Hero not found"
                }
              }
            }
          }
        }
      }
    },
    "/{id}": {
      "get": {
        "tags": [
          "heroes"
        ],
        "summary": "Returns the hero by Id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "example": {
                  "message": "Sucessfuly",
                  "hero": {
                    "hero_id": 1,
                    "name": "Alice",
                    "roles": "Mage",
                    "specialties": "Charge",
                    "lane": "Jungler",
                    "release_year": 2016,
                    "img_hero": "https://images-for-api-ml.vercel.app/alice"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Hero not found try another id"
                }
              }
            }
          }
        }
      }
    },
    "/roles/{role}": {
      "get": {
        "tags": [
          "heroes"
        ],
        "summary": "Returns the hero by role",
        "parameters": [
          {
            "name": "role",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "example": {
                  "message": "Sucessfuly",
                  "hero": {
                    "hero_id": 1,
                    "name": "Alice",
                    "roles": "Mage",
                    "specialties": "Charge",
                    "lane": "Jungler",
                    "release_year": 2016,
                    "img_hero": "https://images-for-api-ml.vercel.app/alice"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "message": "No heroes found for this role"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {}
}